// Keeps the <link rel="modulepreload"> block in index.html in sync with the real import graph.
//   node scripts/gen-preload.mjs          rewrite the block
//   node scripts/gen-preload.mjs --check  exit 1 if index.html is stale (preload.test.js runs the same check)
// Preloading every module (and the two CDN modules) at once flattens the import waterfall: the browser would otherwise discover
// each level of imports only after the previous level arrived, one round trip per level. The inline loader in index.html also
// counts these links' load events to show honest "FETCHING ENGINE n/N" progress.
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const ENTRIES = ['boot-progress.js', 'physics-init.js', 'game.js', 'title-intro.js', 'title-scene.js'];
export const START = '<!-- preload:start (generated by scripts/gen-preload.mjs) -->';
export const END = '<!-- preload:end -->';

const IMPORT_RE = /(?:^|[;\s}])(?:import|export)\s*(?:[^'";(]*?from\s*)?['"]([^'"]+)['"]/g;

/** Breadth-first walk of static imports. Returns {local: [file...], cdn: [url...]}; entries first, then by depth. */
export function importGraph(root = ROOT, entries = ENTRIES) {
  const seen = new Set(), local = [], cdn = [];
  let layer = entries.slice();
  while (layer.length) {
    const next = [];
    for (const f of layer) {
      if (seen.has(f)) continue;
      seen.add(f); local.push(f);
      const src = fs.readFileSync(path.join(root, f), 'utf8');
      for (const m of src.matchAll(IMPORT_RE)) {
        const spec = m[1];
        if (/^https:\/\//.test(spec)) { if (!cdn.includes(spec)) cdn.push(spec); }
        else if (spec.startsWith('./')) next.push(spec.slice(2));
      }
    }
    layer = next;
  }
  return {local, cdn};
}

export function preloadBlock(root = ROOT) {
  const {local, cdn} = importGraph(root);
  const lines = [START];
  for (const u of cdn) lines.push(`    <link rel="modulepreload" href="${u}" crossorigin />`);
  for (const f of local) lines.push(`    <link rel="modulepreload" href="./${f}" />`);
  lines.push('    ' + END);
  return lines.join('\n');
}

export function currentBlock(html) {
  const a = html.indexOf(START), b = html.indexOf(END);
  if (a < 0 || b < 0) return null;
  return html.slice(a, b + END.length);
}

export function rewrite(html, root = ROOT) {
  const a = html.indexOf(START), b = html.indexOf(END);
  if (a < 0 || b < 0) throw new Error('preload markers missing in index.html');
  return html.slice(0, a) + preloadBlock(root) + html.slice(b + END.length);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const file = path.join(ROOT, 'index.html'), html = fs.readFileSync(file, 'utf8'), out = rewrite(html);
  if (process.argv.includes('--check')) { if (out !== html) { console.error('index.html preload block is stale: run node scripts/gen-preload.mjs'); process.exit(1); } }
  else { fs.writeFileSync(file, out); console.log('preload block updated'); }
}
